version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - app-net
    env_file:
      - .env

  wordpress:
    image: wordpress
    networks:
      - app-net
    env_file:
      - .env

  db:
    image: mariadb
    networks:
      - app-net
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  # Add this line
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env

  pma:
    image: phpmyadmin/phpmyadmin
    networks:
      - app-net
    env_file:
      - .env
    ports:
      - "8080:80"

networks:
  app-net:
